config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order('created_at DESC')
  end
  
  def new
  end 
  
  def create 
    @post = Post.new(post_params)
    @post.save
    
    redirect_to @post
  end
  
  def show
    @post = Post.find_by(params[:id])
  end
  
  private
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
	<div class="post_wrapper">
		<h2 class="title"><%= link_to post.title, post %></h2>
		<p class="date"><%= post.created_at.strftime("%B %d, %Y") %></p>
	</div>
<% end %>

app/views/posts/new.html.erb
<h1> New Post </h1>

<%= form_for :post, url: posts_path do |f|  %>
  <p>  
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  
  <p> 
    <%= f.label :body %><br>
    <%= f.text_area :body%>
  </p>
  
  <p>
    <%= f.submit %>
  </p>  
<% end %>

app/views/posts/show.html.erb
<h1 class="title">
  <%= @post.title%>
</h1>

<p class="date">
  Submitted <%= time_ago_in_words(@post.created_at) %> Ago
</p>

<p class="body">
  <%= @post.body %>
</p>